apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: editor-api
      labels:
        app: spring-api
    spec:
      containers:
        - name: editor-api
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_database
          image: localhost:32000/video-editor
          ports:
            - containerPort: 8080

  selector:
    matchLabels:
      app: spring-api
