apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor-ui
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: editor-ui
      labels:
        app: spring-ui
    spec:
      containers:
        - name: editor-ui
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: spring-ui
